### ISSUE TITLE
CNAME segfault

### ISSUE THREAD

**Issue by smeinecke** [zmap/zdns#20]
There seems to be some kind of error in parsing corrupt? CNAME response:

```
# echo "0000000000.xyz" | zdns A
INFO[0000] no name servers specified. will use: 127.0.1.1:53, 10.230.101.10:53, 192.168.130.100:53, 192.168.130.200:53, 192.168.130.103:53, 192.168.130.205:53, 192.168.130.12:53, 10.230.101.14:53, 10.230.101.12:53, 10.230.101.11:53, 10.230.101.7:53, 10.230.101.1:53, 10.230.101.6:53, 10.230.101.18:53, 10.230.101.20:53
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5913ce]

goroutine 59 [running]:
panic(0x740d60, 0xc82000e0b0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/zmap/zdns/modules/miekg.parseAnswer(0x7f9053e7b110, 0xc820252780, 0xc82000aac0)
        /go/src/github.com/zmap/zdns/modules/miekg/mkieg.go:58 +0x64e
github.com/zmap/zdns/modules/miekg.DoLookup(0xc8200f2000, 0xc8200f2060, 0xc82000aac0, 0x12, 0x490001, 0xc82010c000, 0xe, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/zmap/zdns/modules/miekg/mkieg.go:101 +0x4aa
github.com/zmap/zdns/modules/a.(*Lookup).DoLookup(0xc8200ee020, 0xc82010c000, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/zmap/zdns/modules/a/a.go:32 +0xd2
github.com/zmap/zdns.doLookup(0xc82000ea70, 0xc820088960, 0xc820010660, 0xc8200106c0, 0xc820010720, 0xc82000ec70, 0x0, 0x0)
        /go/src/github.com/zmap/zdns/lookup.go:91 +0x5c2
created by github.com/zmap/zdns.DoLookups
        /go/src/github.com/zmap/zdns/lookup.go:188 +0x2c1

```

**Comment by zakird** [comment]
Sorry about that, and thanks for the PR!
