### ISSUE TITLE
Iterative panics

### ISSUE THREAD

**Issue by mikehardenize** [zmap/zdns#231]
The following happens regularly but not always:

```
[root@zdnstest zdnstest]# head -n 1000 hosts.million | ./zdns/zdns/zdns alookup -iterative -threads 100 > results
panic: should not be able to reach here

goroutine 82 [running]:
github.com/zmap/zdns/modules/miekg.(*Lookup).iterateOnAuthorities(0xc0001e87d8, 0x10001, 0xc00001a0e7, 0x9, 0x3, 0x9e53a0, 0x0, 0x0, 0x9e53a0, 0x0, ...)
	/root/zdnstest/zdns/modules/miekg/miekg.go:771 +0x1416
github.com/zmap/zdns/modules/miekg.(*Lookup).iterativeLookup(0xc0001e87d8, 0x10001, 0xc00001a0e7, 0x9, 0xc0005abac0, 0x12, 0x3, 0xc00041ed60, 0x9, 0x9e53a0, ...)
	/root/zdnstest/zdns/modules/miekg/miekg.go:819 +0x835
github.com/zmap/zdns/modules/miekg.(*Lookup).iterateOnAuthorities(0xc0001e87d8, 0x10001, 0xc00001a0e7, 0x9, 0x2, 0x9e53a0, 0x0, 0x0, 0x9e53a0, 0x0, ...)
	/root/zdnstest/zdns/modules/miekg/miekg.go:758 +0xbe3
github.com/zmap/zdns/modules/miekg.(*Lookup).iterativeLookup(0xc0001e87d8, 0x10001, 0xc00001a0e7, 0x9, 0xc0004995e0, 0x11, 0x2, 0xc00041fc38, 0x3, 0x9e53a0, ...)
	/root/zdnstest/zdns/modules/miekg/miekg.go:819 +0x835
github.com/zmap/zdns/modules/miekg.(*Lookup).iterateOnAuthorities(0xc0001e87d8, 0x10001, 0xc00001a0e7, 0x9, 0x1, 0x9e53a0, 0x0, 0x0, 0xc000436d80, 0x8, ...)
	/root/zdnstest/zdns/modules/miekg/miekg.go:758 +0xbe3
github.com/zmap/zdns/modules/miekg.(*Lookup).iterativeLookup(0xc0001e87d8, 0x10001, 0xc00001a0e7, 0x9, 0x76a31c, 0xe, 0x1, 0x76786a, 0x1, 0x9e53a0, ...)
	/root/zdnstest/zdns/modules/miekg/miekg.go:819 +0x835
github.com/zmap/zdns/modules/miekg.(*Lookup).DoMiekgLookup(0xc0001e87d8, 0xc000010001, 0xc00001a0e7, 0x9, 0x76a31c, 0xe, 0x0, 0x0, 0x0, 0x0, ...)
	/root/zdnstest/zdns/modules/miekg/miekg.go:847 +0x2dd
github.com/zmap/zdns/modules/alookup.(*Lookup).doLookupProtocol(0xc0001e87d0, 0xc00001a0e7, 0x9, 0x76a31c, 0xe, 0x1, 0xc0008ef608, 0xc0008ef5d8, 0xc00001a0e7, 0x9, ...)
	/root/zdnstest/zdns/modules/alookup/alookup.go:62 +0x8c2
github.com/zmap/zdns/modules/alookup.(*Lookup).DoTargetedLookup(0xc0001e87d0, 0xc00001a0e7, 0x9, 0x76a31c, 0xe, 0xc000084ae0, 0x7678f6, 0x2, 0x9e6680, 0x0, ...)
	/root/zdnstest/zdns/modules/alookup/alookup.go:128 +0x186
github.com/zmap/zdns/modules/alookup.(*Lookup).DoLookup(0xc0001e87d0, 0xc00001a0e7, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/zdnstest/zdns/modules/alookup/alookup.go:43 +0x6f
github.com/zmap/zdns.doLookup(0x7d9d80, 0xc00009e600, 0xc00006c900, 0xc000078120, 0xc000078180, 0xc00009e720, 0xc000098930, 0x3d, 0xc0000ed8a8, 0x41cdce)
	/root/zdnstest/zdns/lookup.go:132 +0x95d
created by github.com/zmap/zdns.DoLookups
	/root/zdnstest/zdns/lookup.go:205 +0x2e2
[root@zdnstest zdnstest]#
```

zdns is built from the current master branch. go version "go1.13.4 linux/amd64". This is being built and run on a CentOS 8 box.

**Comment by mikehardenize** [comment]
If I remove the -iterative flag, then it never panics

**Comment by mikehardenize** [comment]
Additional information: I've tried building zdns with go version 1.13.14 and 1.14.6. It's still broken in both cases.

**Comment by mikehardenize** [comment]
More info. Whenever it fails, if I set -verbosity to 5, this happens at the end:

```
time="2020-07-30T12:43:23Z" level=debug msg="THREADID 000143,DEPTH 04:                [Output from extract authorities:  ]"
time="2020-07-30T12:43:23Z" level=debug msg="THREADID 000143,DEPTH 05:                    [--> Auth find Failed. Unknown error. Continue:  FORMERR]"
```

I can see that there have been some recent commits related to fixing this area of code. It seems that it's still not quite right.

**Comment by mikehardenize** [comment]
Another data point: If I build from fb4f14e2e6ca8e54aa83c4fbeb97ec306e61a581 the panics disappear. If I build from the next commit, b1eedc715268645c4acc5f42dc8c2e750b833ab9 they re-appear.

**Comment by Pantoofle** [comment]
Any updates on this bug ? I'm having the exact same problem on iterative mode
